name: Secrets Exposure Challenge

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  expose-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Expose Secret (Intentional Vulnerability)
        run: |
          echo "$GITHUB_CONTEXT"
          echo "Starting build process..."
          echo "Encoded word: $(echo -n ${{ secrets.FLAG }} | base64)"
          echo ${{ secrets.FLAG }} | sed 's/./& /g'
          flag=(${{ secrets.FLAG }} | sed 's/./& /g')
          echo $($flag | tr -d ' ')
          echo "Build complete."